### ISSUE TITLE
Firefox addon failing with **** v2.0.60

### ISSUE THREAD

**Issue by abhinavkssk** [anxdpanic/Trakt2KodiAddon-Extension#1]
Hi,

Since a few days, this addon keeps throwing the following error when i try to invoke the **** addon - Any idea what's causing it ?

**Comment by anxdpanic** [comment]
findsource would be coming from output format #4 I believe (not compatible), double check you haven't inadvertently changed the output format / profile.

**Comment by abhinavkssk** [comment]
Ah! Yes it was indeed set to 4. Thanks! Closing the issue now. What do the 5 output formats correspond to ?

**Comment by anxdpanic** [comment]
I don't recall which # is for which tbh, I wrote 1, 3-5 based on the most common trakt add-ons. (if you have any installed experiment with different add-on id's in another profile using 'Open')

#2 had no add-on, but may now if a dev has taken that on that I'm not aware of. 

The idea being add-ons could also be written to match the requests as well and no single output would be for a specific add-on in the end. I just haven't gotten around to documenting all of that, I'll see about adding an add-on compatible with format # table when I do though :)
