### ISSUE TITLE
Add more info to the readme

### ISSUE THREAD

**Issue by cffm** [anxdpanic/Trakt2KodiAddon-Extension#3]
Hi,

seriously, great idea! But it took me a while to figure out how to set this up. Imagine your mom would want to use it... can you describe it a bit more in a how-to/readme?

Also, I tried it with *** and ***. It does something and poof... that is it. What add ons are supported? And how?

**Comment by anxdpanic** [comment]
No specific add-ons are supported, the intention is the reverse actually.
The idea being add-ons could also be written to match the requests as well and no single output would be for a specific add-on in the end. I just haven't gotten around to documenting all of that, I'll see about adding an add-on compatible with format # table when I do though :)
